### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by adityaarun1** [ClementPinard/SfmLearner-Pytorch#10]
Hi,

Is there a pre-trained PyTorch model trained on Cityscapes and Kitti available? The script `models/download_model.sh` and `download_model_5frame.sh` doesn't work.

**Comment by ClementPinard** [comment]
models that can be downloaded are for tensorflow (in original implementation, from tinghuiz). No current conversion is avalaible.
I may had from scratch networks some day, but my results are not as good as original paper's claim.
