### ISSUE TITLE
Hello, how to visualize the true value of the depth map.

### ISSUE THREAD

**Issue by yangbinchao** [ClementPinard/SfmLearner-Pytorch#106]
I want to compare my prediction performance by visualizing the true value of the picture(depth). How to display the ground_truth of the depth map?

**Comment by heroybc** [comment]
> Hi,
> 
> you can easily log the ground truth with the `tensor2array` function.
> Here, in a very similar project, I made a little function that logs best and worst results that you can work on : https://github.com/ClementPinard/unsupervised-depthnet/blob/master/test_depth.py#L50
> 
> Note that the depth here is only a bunch of lidar rays, so not continuous.

Thank you very much. That solved my problem

**Comment by heroybc** [comment]
Thank you for your reply, how can this kind of GT be generated ?

![图片1](https://user-images.githubusercontent.com/47782077/99618504-5ec10d00-2a5c-11eb-8577-ac874c29c18f.png)

**Comment by heroybc** [comment]
> Hi,
> 
> you can easily log the ground truth with the `tensor2array` function.
> Here, in a very similar project, I made a little function that logs best and worst results that you can work on : https://github.com/ClementPinard/unsupervised-depthnet/blob/master/test_depth.py#L50
> 
> Note that the depth here is only a bunch of lidar rays, so not continuous.

Thank you for your reply, how can this kind of GT be generated ?

![图片1](https://user-images.githubusercontent.com/47782077/99618631-a47dd580-2a5c-11eb-85ae-5da54f58e1e8.png)

**Comment by ClementPinard** [comment]
Hi, doing chores to clean up mi issue list, the visualization above can be obtained through scipy ND interpolator. See https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LinearNDInterpolator.html#scipy.interpolate.LinearNDInterpolator

So you just need to use this function to get the 3d points from lidar, and https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/data/kitti_raw_loader.py#L165 then use scipy's function to construct the interpolated depth map.

Note that it won't be accurate so it's only for vizualisation purpose.
