### ISSUE TITLE
kitti_util error

### ISSUE THREAD

**Issue by will8able** [ClementPinard/SfmLearner-Pytorch#111]
Successfully downloaded KITTI dataset and attempted to run the prepare_train_data.py command  as shown below:

> !python3 data/prepare_train_data.py /content/SfmLearner-Pytorch/kitti/raw --dataset-format 'kitti_raw' --dump-root /content/SfmLearner-Pytorch/kitti/formatted --width 416 --height 128 --num-threads 4

The following error is given:

> Traceback (most recent call last):
  File "data/prepare_train_data.py", line 130, in <module>
    main()
  File "data/prepare_train_data.py", line 69, in main
    from kitti_raw_loader import KittiRawLoader
  File "/content/SfmLearner-Pytorch/data/kitti_raw_loader.py", line 6, in <module>
    from kitti_util import pose_from_oxts_packet, generate_depth_map, read_calib_file, transform_from_rot_trans
ModuleNotFoundError: No module named 'kitti_util'

I could not find kitti_util.py in the GitHub, is there something I am missing? I can confirm all requirements were installed as well beforehand. Thank you very much.

**Comment by ClementPinard** [comment]
Ooops ! Did a commit this week and forgot to include new files in the commit.

I just pushed them, it should be fine now. BTW it is now working on kitti_odometry too !

**Comment by will8able** [comment]
Thank you so much! Big fan of your research from a Hopkins undergrad :)

**Comment by will8able** [comment]
Thank you so much! Big fan of your research from a Hopkins undergrad :)
