### ISSUE TITLE
depth images seem the same

### ISSUE THREAD

**Issue by JIAJIAqi-1** [ClementPinard/SfmLearner-Pytorch#119]
Hi! Thank you very much for your work. When I try to plot depth images, I found the results is exactly the same. How can I get the depth images in the paper? Thanks! 
![000000_depth](https://user-images.githubusercontent.com/81906135/114009361-a8888380-9895-11eb-99ed-65f70720a3b6.png)
![004540_depth](https://user-images.githubusercontent.com/81906135/114009368-a9b9b080-9895-11eb-8602-80c551bab559.png)

**Comment by ClementPinard** [comment]
Hi, what were the input images ? It is expected that the depth more or less follow the same distribution because it has only been trained with KITTI images. However the depth should not always be the same.

**Comment by JIAJIAqi-1** [comment]
Thank you for your quick reply!
I used the pretrained nets(dispnet_model_best.pth.tar) you posted on https://drive.google.com/drive/folders/1H1AFqSS8wr_YzwG2xWwAQHTfXN5Moxmx.
And the input images are KITTI-rawdata-road like these
![0000000000](https://user-images.githubusercontent.com/81906135/114024811-12f5ef80-98a7-11eb-9a56-b9f972282459.png)
![0000000282](https://user-images.githubusercontent.com/81906135/114024840-19846700-98a7-11eb-8c25-c7aeac335582.png)

**Comment by ClementPinard** [comment]
Indeed there should be a better depth for these pictures. What size did you use ? Normally it should 416x128 . I guess you used the run_inference.py script ?
Can you output the disparity instead of depth ? The resulting colored maps are usually more readable

**Comment by JIAJIAqi-1** [comment]
Thank you very much! The reason of the problem is the incorrect size of pictures!

**Comment by ClementPinard** [comment]
great! :)
Closing the issue then. Don't hesitate to reopen if you have further questions
