### ISSUE TITLE
prepare data fail due to file missing

### ISSUE THREAD

**Issue by ynjiun** [ClementPinard/SfmLearner-Pytorch#126]
Traceback (most recent call last):
  File "data/prepare_train_data.py", line 130, in <module>
    main()
  File "data/prepare_train_data.py", line 103, in main
    for _ in tqdm(tasks.result(), total=n_scenes):
  File "/home/paul/pytorch/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/paul/pytorch/lib/python3.6/site-packages/pebble/pool/base_pool.py", line 209, in next
    raise result
FileNotFoundError: [Errno 2] No such file or directory: Path('/home/paul/data/kitti_2011_drive/2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/data/0000000001.bin')

Check kitti_2011_drive/2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/data/  
indeed the directory is empty
I download from kitti again

(pytorch) paul@tensor:~/data/kitti_2011_drive$ ./last_downloader.sh 
Downloading: 2011_10_03_drive_0058_sync.zip
--2021-06-30 22:28:14--  https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_10_03_drive_0058/2011_10_03_drive_0058_sync.zip
Resolving s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)... 52.219.140.27
Connecting to s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)|52.219.140.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60225505 (57M) [application/zip]
Saving to: ‘2011_10_03_drive_0058_sync.zip’

2011_10_03_drive_0058_sync.zip        100%[========================================================================>]  57.43M  8.63MB/s    in 7.7s    

2021-06-30 22:28:22 (7.47 MB/s) - ‘2011_10_03_drive_0058_sync.zip’ saved [60225505/60225505]

Archive:  2011_10_03_drive_0058_sync.zip
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000009.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000022.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000006.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000013.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000007.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000015.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000011.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000001.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000020.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000012.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000018.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000028.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000002.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000026.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000008.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000017.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000016.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000025.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000004.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000021.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000019.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000010.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000000.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000003.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000027.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000005.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000014.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000023.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/data/0000000024.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/dataformat.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/oxts/timestamps.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000006.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000025.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000013.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000018.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000027.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000008.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000015.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000009.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000026.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000007.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000014.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000010.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000023.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000001.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000016.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000000.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000011.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000003.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000019.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000020.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000024.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000017.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000005.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000022.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000021.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000002.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000004.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000012.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/data/0000000028.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_00/timestamps.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000006.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000025.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000013.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000018.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000027.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000008.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000015.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000009.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000026.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000007.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000014.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000010.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000023.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000001.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000016.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000000.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000011.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000003.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000019.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000020.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000024.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000017.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000005.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000022.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000021.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000002.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000004.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000012.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/data/0000000028.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_01/timestamps.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000006.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000025.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000013.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000018.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000027.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000008.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000015.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000009.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000026.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000007.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000014.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000010.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000023.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000001.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000016.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000000.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000011.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000003.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000019.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000020.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000024.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000017.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000005.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000022.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000021.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000002.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000004.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000012.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/data/0000000028.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_02/timestamps.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000006.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000025.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000013.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000018.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000027.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000008.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000015.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000009.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000026.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000007.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000014.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000010.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000023.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000001.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000016.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000000.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000011.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000003.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000019.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000020.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000024.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000017.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000005.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000022.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000021.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000002.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000004.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000012.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/data/0000000028.png  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/image_03/timestamps.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/timestamps_end.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/timestamps.txt  
 extracting: 2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/timestamps_start.txt  

and check again, thre is no file under velodyne_points/data 

Anybody has the same problem? how to fix this? Can we train without this? Please help. Thanks.

**Comment by ynjiun** [comment]
well, I just delete the 0058 directory and run the prepare data again (it took a long time again) to generate the training datasets. Everything is running as expected now.

Not sure why the 2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/data is missing ; (

**Comment by ClementPinard** [comment]
Hi.

From what I understood, This folder has been used for depth benchmark. As such, they removed the raw Lidar scans from this folder to make the groundtruth unavailable. The code was written before they removed it, so its not robust to it, sadly. The solution would be to put it in the training set and not recover its velodyne scan.

**Comment by SBaokun** [comment]
@ynjiun I had the same problem as you. How did you follow up to fix it? Deleted it? Or did you use it in the training set?
