### ISSUE TITLE
 the ground truth depth map

### ISSUE THREAD

**Issue by bizheyandebing** [ClementPinard/SfmLearner-Pytorch#127]
Thank you for your code,

The ground truth depth map interpolated from sparse measurements. I haven't found the code to generate the ground truth depth map. Would you please release the code

**Comment by ClementPinard** [comment]
Hi, you can see the code for depth interpolation here : https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L115

Note that the resulting ground truth is only for vizualisation purpose, it's NOT a ground truth.

**Comment by bizheyandebing** [comment]
> Hi, you can see the code for depth interpolation here : https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L115
> 
> Note that the resulting ground truth is only for vizualisation purpose, it's NOT a ground truth.

非常感谢您，这对我帮助很大。
再次万分感谢
非常感谢您，这对我帮助很大。
再次万分感谢
Thank you very much. 
It helped me a lot.
Thanks again。
