### ISSUE TITLE
what's the minimal files required to train depth only model

### ISSUE THREAD

**Issue by ynjiun** [ClementPinard/SfmLearner-Pytorch#132]
Hi @ClementPinard,

Thank you for sharing this code. This is a great work!

I read your answer on https://github.com/ClementPinard/SfmLearner-Pytorch/issues/108 regarding how to use my video to train the model. I follow the steps and prepared a long sequence of undistorted images and I have cam.txt ready as well. I don't have depth map for each image. So my question is: would the undistorted images + cam.txt be enough to kick off the train.py? Would the following setup good to go?

1. put the sequence of undistorted images and cam.txt under /data/seq1 directory
2. train.txt only has one entry of seq1
3. val.txt is empty
2. python train.py /data/ -b4 -m0.2 -s0.1 --epoch-size 3000 --sequence-length 3 --log-output

Would this adequate? 

Thank you very much for your help.

**Comment by ClementPinard** [comment]
Hello, if you follow the recommendations for camera displacement, yes it might work !

good luck,

Clément
