### ISSUE TITLE
Weird results from pretrained model on KITTI images

### ISSUE THREAD

**Issue by a961009** [ClementPinard/SfmLearner-Pytorch#136]
Thanks for the PyTorch codes!
When I use the pretrained model (https://drive.google.com/drive/folders/1H1AFqSS8wr_YzwG2xWwAQHTfXN5Moxmx) to inference disp and depth on Kitti images, the disp and the depth result looks weird. The disp and the depth change very sharply. The main part of the disp is either 255 or 0, with almost no intermediate value.
![2011_09_26_drive_0011_sync_03-0000000000_disp](https://user-images.githubusercontent.com/48381323/156874950-5d1e438d-a641-45f9-a6a1-f32c56450239.jpg)
![0000000000](https://user-images.githubusercontent.com/48381323/156874953-9a5f6480-bb08-406a-8f0b-3e4fc492ad39.jpg)
![2011_09_26_drive_0011_sync_03-0000000000_depth](https://user-images.githubusercontent.com/48381323/156874954-c925e5da-5731-4448-9ab1-8cda73fc272b.jpg)

**Comment by a961009** [comment]
Here are more results at different scenes
![2011_09_26_drive_0001_sync_02-0000000039_displayImage](https://user-images.githubusercontent.com/48381323/156875625-221ecffd-6573-43ca-8997-a3883b9aefb3.jpg)
![2011_09_26_drive_0009_sync_02-0000000375_displayImage](https://user-images.githubusercontent.com/48381323/156875633-dd49ce53-9dee-46d5-82c4-e93b5defc422.jpg)
![2011_09_26_drive_0015_sync_02-0000000266_displayImage](https://user-images.githubusercontent.com/48381323/156875636-1a142305-5b98-4e52-abf0-b3b25012f795.jpg)

**Comment by a961009** [comment]
https://github.com/ClementPinard/SfmLearner-Pytorch/blob/c2374d50f816e976c6889eb5e07198749d953bc6/run_inference.py#L66
should be 
`tensor_img = ((tensor_img/255 - 0.5)/0.5).to(device)`

**Comment by ClementPinard** [comment]
Hi, see #125 as to why we don't divide by 255.

You results are indeed a bit weird. I'll try to reproduce the results to see if something is wrong, will keep you updated.

**Comment by a961009** [comment]
> 

Thanks for your quick reply. After dividing by 255, the results become reasonable as mentioned in original paper. I'll keep you updated, when i find something.
