### ISSUE TITLE
prepare_train_data.py

### ISSUE THREAD

**Issue by shengsli** [ClementPinard/SfmLearner-Pytorch#14]
Hi @ClementPinard 

- I come across some problem when running prepare_train_data.py as follows: 
`python data/prepare_train_data.py C:\TensorFlow\SfmLearner-Pytorch\raw_data_downloader\2011_09_26\2011_09_26_drive_0001_sync --dataset-format "kitti" --dump-root C:\TensorFlow\SfmLearner-Pytorch\formatted_data --width 416 --height 128 --num-threads 4`

- And, it gives me the follwoing error message: 
`Traceback (most recent call last):
  File "data/prepare_train_data.py", line 94, in <module>
    main()
  File "data/prepare_train_data.py", line 67, in main
    get_gt=args.with_gt)
  File "C:\TensorFlow\SfmLearner-Pytorch\data\kitti_raw_loader.py", line 33, in __init__
    self.collect_train_folders()
  File "C:\TensorFlow\SfmLearner-Pytorch\data\kitti_raw_loader.py", line 51, in collect_train_folders                                                                                                      drive_set = (self.dataset_dir/date).dirs()
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\path.py", line 560, in dirs
    return [p for p in self.listdir(pattern) if p.isdir()]
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\path.py", line 545, in listdir
    for child in os.listdir(self)
FileNotFoundError: [WinError 3] The system cannot find the path specified: Path('C:\\TensorFlow\\SfmLearner-Pytorch\\raw_data_downloader\\2011_09_26\\2011_09_26_drive_0001_sync\\2011_09_26')`

- This is a screenshot of my command when running prepare_train_data and error described above: 
![image](https://user-images.githubusercontent.com/29371690/36945847-de09a284-1fab-11e8-84aa-3b6e625f2967.png)

- I tried both relative path and absolute path, and it gives me the same error. I also tried `/` and `\`, but it seems not working. 

- I work on a windows 10 machine and here is my directory structure: 
```
SfmLearner-Pytorch
|-- data
|-- datasets
|-- formatted_data
|-- raw_data_downloader 
|     |-- 2011_09_26
|           |-- 2011_09_26_drive_0001_sync
|           |-- 2011_09_26_drive_0002_sync
|           |-- ..........................................................
```

Thank you in advance.

**Comment by shengsli** [comment]
Hi @ClementPinard 

- I think I maybe find what the problem is. Since I am not familiar with the code, I assumed the `dataset_dir` as one of the dataset subfolders like `2011_09_26_drive_0001_sync`. I change the dataset_dir to `..\SfmLearner-Pytorch\raw_data_downloader`. And now it starts retrieving frames. 

- But, I have a new issue now that `NameError: name 'data_loader' is not defined`. I include part of the error message below: 
```
C:\TensorFlow\SfmLearner-Pytorch>python data/prepare_train_data.py C:\TensorFlow\SfmLearner-Pytorch\raw_data_downloader --dataset-format kitti --dump-root C:\TensorFlow\SfmLearner-Pytorch\formatted_data --width 416 --height 128 --num-threads 4
Retrieving frames
  0%|                                                                     | 0/24 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\_parallel_backends.py", line 350, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\TensorFlow\SfmLearner-Pytorch\data\prepare_train_data.py", line 27, in dump_example
    scene_list = data_loader.collect_scenes(scene)
NameError: name 'data_loader' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\_parallel_backends.py", line 359, in __call__
    raise TransportableException(text, e_type)
joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
NameError                                          Sun Mar  4 19:22:09 2018
PID: 2692Python 3.6.2: C:\Users\sheng\AppData\Local\Programs\Python\Python36\python.exe
...........................................................................
C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function dump_example>, (Path('C:\\TensorFlow\\SfmLearner-Pytorch\\raw_da...nloader\\2011_09_26\\2011_09_26_drive_0001_sync'),), {})]
    132
    133     def __len__(self):
    134         return self._size
    135

...........................................................................
C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function dump_example>
        args = (Path('C:\\TensorFlow\\SfmLearner-Pytorch\\raw_da...nloader\\2011_09_26\\2011_09_26_drive_0001_sync'),)
        kwargs = {}
    132
    133     def __len__(self):
    134         return self._size
    135

...........................................................................
C:\TensorFlow\SfmLearner-Pytorch\data\prepare_train_data.py in dump_example(scene=Path('C:\\TensorFlow\\SfmLearner-Pytorch\\raw_da...nloader\\2011_09_26\\2011_09_26_drive_0001_sync'))
     22
     23 args = parser.parse_args()
     24
     25
     26 def dump_example(scene):
---> 27     scene_list = data_loader.collect_scenes(scene)
        scene_list = undefined
        scene = Path('C:\\TensorFlow\\SfmLearner-Pytorch\\raw_da...nloader\\2011_09_26\\2011_09_26_drive_0001_sync')
     28     for scene_data in scene_list:
     29         dump_dir = args.dump_root/scene_data['rel_path']
     30         dump_dir.makedirs_p()
     31         intrinsics = scene_data['intrinsics']

NameError: name 'data_loader' is not defined
___________________________________________________________________________
```
Thanks for taking your time.

**Comment by ClementPinard** [comment]
Hello, thanks for trying this code for Windows !

I did some research on your problem (which does not appear on Linux) here is some doc about it : http://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/


Basically global variables are not shared with multi threaded function Windows while they are in Linux.

I'll get a fix tomorrow. In the mean time you can add the data loader as an argument to the function dump_example or replace the multi thread command with a simple for loop.

Cheers,

Clément

**Comment by ClementPinard** [comment]
before I push the changes, as I am not on windows, I need you to test it :
can you change [this line](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/data/prepare_train_data.py#L26) to `def dump_example(scene, data_loader):`

and [this line](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/data/prepare_train_data.py#L75) to `Parallel(n_jobs=args.num_threads)(delayed(dump_example)(scene, data_loader) for scene in tqdm(data_loader.scenes))` ?

It should pass the data_loader to the function, and let it access it on windows (not needed on linux)

thanks

**Comment by ClementPinard** [comment]
Unfortunately no official support for windows pytorch yet, but I heard about unofficial builds, although it's still experimental
you might want to check this out for example :https://github.com/peterjc123/pytorch-scripts

Thanks anyway for your input ! Glad to know how to make my code windows ready ;)
