### ISSUE TITLE
Seq 10 is not in the test_secens.txt

### ISSUE THREAD

**Issue by AlbertOh90** [ClementPinard/SfmLearner-Pytorch#157]
Hello Clement! 

Thanks for sharing your work. 
Just find out that there is a mapping between the KITTI raw data and KITTI odometry data 
mapping = {
    "2011_10_03_drive_0027": "00",
    "2011_10_03_drive_0042": "01",
    "2011_10_03_drive_0034": "02",
    "2011_09_26_drive_0067": "03",
    "2011_09_30_drive_0016": "04",
    "2011_09_30_drive_0018": "05",
    "2011_09_30_drive_0020": "06",
    "2011_09_30_drive_0027": "07",
    "2011_09_30_drive_0028": "08",
    "2011_09_30_drive_0033": "09",
    "2011_09_30_drive_0034": "10"
}
(https://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chen_Selective_Sensor_Fusion_CVPR_2019_supplemental.pdf)
However, the sequence 09 and 10 are not listed in the test_scences.txt. 
Does it mean that we should not use 09 and 10 for evaluation if the model is trained on the KITTI_raw_data that is prepared by the provided command. 

Thanks!

**Comment by ClementPinard** [comment]
Hello,

yes Indeed. If you want to test odometry, you need to remove sequence 09 and 10 from training.

I did not spend too much time on this matter, and someone else pointed it out in the past : #67

I anyone wants to provide a training recipe especially for odometry and share the weights, they're welcome to do so ! :smile:

**Comment by AlbertOh90** [comment]
I did not check the previous questions. Got it and Thank you for your quick reply!
