### ISSUE TITLE
test_disp.py fails with the recent commits

### ISSUE THREAD

**Issue by anuragranj** [ClementPinard/SfmLearner-Pytorch#19]
There were some changes to `test_disp.py`, and `kitti_eval/depth_evaluation_utils.py` in the recent commits, which results in the following error while testing: (The old version still works)
```sh
  File "test_disp.py", line 160, in <module>
    main()
  File "test_disp.py", line 61, in main
    framework = test_framework(dataset_dir, test_files, seq_length, args.min_depth, args.max_depth)
  File "kitti_eval/depth_evaluation_utils.py", line 14, in __init__
    self.calib_dirs, self.gt_files, self.img_files, self.displacements, self.cams = read_scene_data(self.root, test_files, seq_length, step)
  File "kitti_eval/depth_evaluation_utils.py", line 99, in read_scene_data
    displacements.append(get_displacements(data_root/date/scene/'oxts', ref_indices, demi_length))
  File "kitti_eval/depth_evaluation_utils.py", line 60, in get_displacements
    reordered_indices = [indices[tgt_index]] + [*indices[:tgt_index]] + [*indices[tgt_index + 1:]]
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by ClementPinard** [comment]
Yes, sorry about that, should have been more careful when pushing.

This has been solved in commit #69588b0  (3 hours ago)

I'm still struggling to get comparable results with original paper so some other change might occur in the next days. Thanks for your vigilance anyway !

**Comment by anuragranj** [comment]
Thanks. Do these changes in depth evaluation result in different scores too? How similar/different is it to Eigen et al?

**Comment by ClementPinard** [comment]
The difference here is that in addition to determining depth scale_factor from ratio of medians, we try to get it from ratio of translations. The main idea is that getting median of GT depth is impossible in real condition, while getting GT displacement is.

Obviously this leads to worse results but it's closer to a real usecase.

Anyway, we compute both from depth ratio and from translation ratio.
Besides, with the option `--output-dir` you can save your inference values in a npy file that you can feed to e.g. Zhou et al. [test_disp](https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/eval_depth.py) script. To be absolutely sure that tests are consistent.

**Comment by anuragranj** [comment]
Ok cool. Thanks.
