### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by mathmanu** [ClementPinard/SfmLearner-Pytorch#2]
**The training is not using multi-gpus. If you just add DataParallel(), it will use all the GPUs in th system - snippet from train.py below:**

    if args.pretrained_disp:
        print("=> using pre-trained weights for Dispnet")
        a = torch.load(args.pretrained_disp)
        disp_net.load_state_dict(a['state_dict'])
    else:
        disp_net.init_weights()

    disp_net = torch.nn.DataParallel(disp_net).cuda()
    pose_exp_net = torch.nn.DataParallel(pose_exp_net).cuda()
            
    cudnn.benchmark = True
    print('=> setting adam solver')

    parameters = set()
    for net_ in [disp_net, pose_exp_net]:
        parameters |= set(net_.parameters())

**When using multi-gpu training, you have to do some changes in inference, while loading he checkpoint:**
    disp_net = models.DispNetS().cuda()
    weights = torch.load(args.ckpt_file)
    
    #if the original model was created with DataParallel, remove it.
    new_state_dict = OrderedDict()
    for k, v in weights['state_dict'].items():
        # remove `module.`
        name = k[7:] if k.startswith('module.') else k
        new_state_dict[name] = v
    weights['state_dict'] = new_state_dict
    
    disp_net.load_state_dict(weights['state_dict'])

**Comment by ClementPinard** [comment]
Thanks for the suggestion! I did not take the time to make it multi GPU because the recommended batchsize is 4.
Also you don't need to change the state_dict that way if you save dispnet.module instead of dispnet.

I'll try to add the snippet within a day or two!

**Comment by ClementPinard** [comment]
Done
