### ISSUE TITLE
Can not reproduce pose results.

### ISSUE THREAD

**Issue by anuragranj** [ClementPinard/SfmLearner-Pytorch#23]
I am getting the following with the pretrained models, which are much worse than reported here. https://github.com/ClementPinard/SfmLearner-Pytorch#pose-results
It is possible that the pretrained models in google drive are not updated.

```sh
$ python test_pose.py ../SfmLearner-Pytorch/pretrained/exp_pose_model_best.pth.tar --dataset-dir kitti/odometry/ --sequence 09
getting test metadata for theses sequences : {Path('kitti/odometry/sequences/09')}
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.50it/s]
1591 snippets to test
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 1587/1591 [02:35<00:00, 10.20it/s]

Results
	        ATE,         RE
mean 	     0.0195,     0.0041
std 	     0.0106,     0.0022
$ python test_pose.py ../SfmLearner-Pytorch/pretrained/exp_pose_model_best.pth.tar --dataset-dir kitti/odometry/ --sequence 10
getting test metadata for theses sequences : {Path('kitti/odometry/sequences/10')}
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
1201 snippets to test
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 1197/1201 [03:11<00:00,  6.24it/s]

Results
	        ATE,         RE
mean 	     0.0148,     0.0042
std 	     0.0096,     0.0026

**Comment by ClementPinard** [comment]
Looks rather like the evaluation code changed. I encountered the same problem actually, and the pose network has not been updated since the README has been changed. (so I think it's the same that got me these results in the README)
The strange thing is I cannot revert to a commit where I got these results.
I'll let you know if I can retrieve the results or at least how I got them. If nothing works, I'll have to update the README :(

**Comment by anuragranj** [comment]
Thanks Clement. I think I would be rather nice, if it is consistent with Zhou et al's SfmLearner code.

**Comment by ClementPinard** [comment]
Can you try `pose_exp_checkpoints.pth.tar` In the drive folder? I get better results on sequence 9 and 10.
sequence 9
```
Results
                ATE,         RE
mean         0.0141,     0.0031
std          0.0084,     0.0020
```

10
```
Results
                ATE,         RE
mean         0.0116,     0.0031
std          0.0084,     0.0019
```

RE is worse than initially reported but that's not really important as we didn't have absolute values to match with. I think it's due to measure not being the same way as before.

If you get the same results, I'll update the README

**Comment by anuragranj** [comment]
I get worse. Is the commit in this repo same as your local?
```sh
$ python test_pose.py ~/Downloads/exp_pose_checkpoint.pth.tar --dataset-dir kitti/odometry/ --sequence 09 
getting test metadata for theses sequences : {Path('kitti/odometry/sequences/09')}
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.37it/s]
1591 snippets to test
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 1587/1591 [02:35<00:00, 10.22it/s]

Results
	        ATE,         RE
mean 	     0.0190,     0.0126
std 	     0.0107,     0.0072

**Comment by ClementPinard** [comment]
Just tested with a clean clone and explicitely re-downlaoding the model from the drive gives me the same results as i initially gave to you. What are your results on seq10 ?

**Comment by anuragranj** [comment]
The outputs looks quite different. I am using the latest exp_pose_checkpoint.pth.tar from google drive. There are my predictions.
[predictions.npy.zip](https://github.com/ClementPinard/SfmLearner-Pytorch/files/1956058/predictions.npy.zip)


```python
import numpy as np
my_pred = np.load('outputs/predictions.npy')
cl_pred = np.load('~/Downloads/predictions.npy')
np.linalg.norm(my_pred - cl_pred)
6.580990918123095

(my_pred - cl_pred).max()
0.5381976059729281

(my_pred - cl_pred).min()
-0.2857733567663465

**Comment by ClementPinard** [comment]
what are your pytorch and numpy versions ? mine:

```
numpy==1.14.0
torch==0.3.1
```

**Comment by anuragranj** [comment]
They are same as well.
```python
In [3]: torch.__version__
 '0.3.1'
numpy.__version__
'1.14.0'

**Comment by ClementPinard** [comment]
It's starting to be very weird ! :(
I you have any idea in why we get inconsistent results, I'm running out of them !

**Comment by anuragranj** [comment]
What's your python version? I am using Python 3.5.2

Are you also using the data downloaded from:
http://kitti.is.tue.mpg.de/kitti/data_odometry_poses.zip
http://kitti.is.tue.mpg.de/kitti/data_odometry_color.zip

The md5sum of the network I downloaded is
9cc9b4b9839971769596052be241d2d7  exp_pose_checkpoint.pth.tar
The md5sum of data I downloaded is 
3a0e3b5db6625780a673a4b535e88b78  data_odometry_poses.zip
<takes too long to compute, will add it soon> data_odometry_color.zip
Could you verify these?

Also, could you maybe zip the test sequences 9 and 10, and pose test data, and put in the google drive? I want to make sure we are testing on the same sequences.

**Comment by ClementPinard** [comment]
Oh, did not see the image height and width you were using (its cropped out in github)

You are using 418 and not 416. Can you try with 128x416 input ?

**Comment by anuragranj** [comment]
Ah that was the bug I think. I get
```sh
 Result on seq 10. 
                ATE,         RE
mean         0.0116,     0.0031
std          0.0084,     0.0019
Results on seq 9. 
Results
                ATE,         RE
mean         0.0141,     0.0031
std          0.0084,     0.0020

**Comment by anuragranj** [comment]
Thanks so much :)
