### ISSUE TITLE
inconsistent depth evaluation code with the original author

### ISSUE THREAD

**Issue by haofeixu** [ClementPinard/SfmLearner-Pytorch#31]
Hi, @ClementPinard , great pytorch implementation of sfmlearner!

But when I evaluate the same depth prediction results using your evaluation code [test_disp.py](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/test_disp.py) and the original author's [eval_depth.py](https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/eval_depth.py), I got inconsistency results.

After some experiments, I found you clip the predicted depth value to [min_depth, max_depth] first, then compute the scale factor, as in [loss_functions.py](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/14ed93e346fbf9f81269fe6684760359cb157a2e/loss_functions.py#L102-L104) : 
```
valid_pred = current_pred[valid].clamp(1e-3, 80)

valid_pred = valid_pred * torch.median(valid_gt)/torch.median(valid_pred)
```
However, the original author computed the scale factor first, then clip the predicted depth, as in [eval_depth.py](https://github.com/tinghuiz/SfMLearner/blob/f68b1528a0bcb5692589658dc35803232fb34139/kitti_eval/eval_depth.py#L66-L70):
```
scalor = np.median(gt_depth[mask])/np.median(pred_depth[mask])
pred_depth[mask] *= scalor

pred_depth[pred_depth < args.min_depth] = args.min_depth
pred_depth[pred_depth > args.max_depth] = args.max_depth
```
This does produce different results. By simply modifying [your original code](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/14ed93e346fbf9f81269fe6684760359cb157a2e/loss_functions.py#L102-L104) as
```
valid_pred = current_pred[valid]
valid_pred = valid_pred * torch.median(valid_gt) / torch.median(valid_pred)
valid_pred = valid_pred.clamp(1e-3, 80)
```
we can get the same results when evaluating the same depth predictions as the original author. Also, this inconsistency exists in the [test_disp.py](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/test_disp.py). 

Hope you can fix it, thanks.

**Comment by ClementPinard** [comment]
Hello, thanks for spotting it ! I'm filing a patch. Were the results better with this little change ?

**Comment by haofeixu** [comment]
Actually, this little change only affects the validation step, I haven't tried it yet, maybe you can have a try.
