### ISSUE TITLE
Converting 6DoF to matrix and vice versa

### ISSUE THREAD

**Issue by shahabty** [ClementPinard/SfmLearner-Pytorch#36]
Hello @ClementPinard,
I can convert 6DoF to transformation matrix by calling pose_vec2mat. But, I need to do the reverse to convert transformation matrix to 6DOF. could you please help me to figure this out?

Thanks,

**Comment by ClementPinard** [comment]
Well, this is much tougher than the main transformation ! It involves the function atan2 it's not trivial ;)
After a quick google search, you can try a variation of this proposed algorithm : https://www.learnopencv.com/rotation-matrix-to-euler-angles/
Fortunately, the atan2 function is available in pytorch ! see here https://pytorch.org/docs/stable/torch.html#torch.atan2

Good luck,

**Comment by shahabty** [comment]
Thank you very much for your quick reply.

**Comment by shahabty** [comment]
I wrote this to convert mat to vec in pytorch. Could you please have a look at it and let me know if it is wrong or there is anyway to improve the performance.
```

def pose_mat2vec(Rt):
    t_all = Rt[:,:,-1]
    R_all = Rt[:,:,:3]

    pose_all = []
    for R,t in zip(R_all,t_all):
        sy = torch.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])

        singular = sy < 1e-6
        if not singular :
            x = torch.atan2(R[2,1] , R[2,2])
            y = torch.atan2(-R[2,0], sy)
            z = torch.atan2(R[1,0], R[0,0])
        else :
            x = torch.atan2(-R[1,2], R[1,1])
            y = torch.atan2(-R[2,0], sy)
            z = 0
        theta = torch.FloatTensor([x, y, z]).cuda(0)
        pose_6 = torch.cat((theta, t),0)
        pose_all.append(pose_6)

    pose_all = torch.stack(pose_all,0)
    return pose_all
```


Thanks a lot.

**Comment by ClementPinard** [comment]
your code is unfortunately not differentiable becasue you create a new FloatTensor.
You should just have `theta = torch.stack([x,y,z])`

Other than that, the code is not very parallel, but I guess with the singular check, you cannot do much better. the sy can be computed batchwise however

```python
def pose_mat2vec(Rt):
    t_all = Rt[:,:,-1]
    R_all = Rt[:,:,:3]
    sy = R[:,0,0]^2 + R[:,1,0]^2
    y_all = torch.atan2(-R[:,2,0], sy)
    theta = []
    for (R,t, s) in zip(R_all,t_all, sy, y_all):
        singular = s < 1e-6
        if not singular :
            x = torch.atan2(R[2,1] , R[2,2])
            z = torch.atan2(R[1,0], R[0,0])
        else :
            x = torch.atan2(-R[1,2], R[1,1])
            z = 0
        theta.append(torch.stack([x, y, z]))

    theta = torch.stack(theta)
    pose_all = torch.cat([theta,t_all], dim=1)
    return pose_all
```
