### ISSUE TITLE
interpolate() unexpected keyword argument

### ISSUE THREAD

**Issue by qureshizawar** [ClementPinard/SfmLearner-Pytorch#37]
Got the following error message when using the latest version: 

`tgt_img_scaled = F.interpolate(tgt_img, (h, w), method='area', align_corners=False)
TypeError: interpolate() got an unexpected keyword argument 'method'`

(line 312)

parameters used: --epoch-size 1000 --log-output --with-gt

Changed that line to:

`tgt_img_scaled = F.interpolate(tgt_img, (h, w), mode='area')`

Seems to working now, did I break something? (great job on the port btw! :) )

Thanks!

**Comment by ClementPinard** [comment]
yes, sorry about that, a patch is incoming

**Comment by ClementPinard** [comment]
solved
