### ISSUE TITLE
difference in validation with sparse ground truth and filled ground truth of depth

### ISSUE THREAD

**Issue by sanweiliti** [ClementPinard/SfmLearner-Pytorch#46]
Hi,
The depth predictions are validated with sparse ground truth depths of KITTI here, but there are also other papers validating against full ground truth (filled by interpolating). Will there be a large difference in the validation result between these two methods? Which one is the main criteria nowadays in monocular depth estimation?

**Comment by ClementPinard** [comment]
Officially it is supposed to be the exact same. The depth benchmark is just a ready-to-go depth image instead of LiDar data + calibration.

Now, if you look at other datasets, you can see slight differences, especially with Odometry, where groundtruth pose has probably been smoothed compared to raw data + calibration.

I think it's safe to say that the evaluation is pretty much the same here, because the LiDar and fixed calibration are pretty reliable.

**Comment by koutilya40192** [comment]
@a-jahani Please correct if I am wrong. There are two ways to obtain GT depth for the Kitti test setup (eigen split or kitti split doesn't matter): 1) Calibration + Velodyne data (Lidar) or 2) The official ground truth depth images (un interpolated) provided by the Official Kitti providers. 

People so far (including this work) used to follow 1) but the idea is to slowly shift towards 2) ?? 
If I am not wrong there is an interpolated version (completed depth) of the GT depth images by the offiicial Kitti providers, was it for qualitative comparisons only? The sparse (un interpolated) GT depth (obtained either from 1) or 2)) should alone be used for quantitative evaluation like how everyone in this field reported?

**Comment by a-jahani** [comment]
@koutilya40192 Yes you are right in all of your sentences. evaluating on 1) is not good as the ground truth is wrong 2) is better but still it is not dense so your algorithm might predict very wrong result on those regions but it wont affect the numbers.

There is no interpolated version (completed depth) of the GT depth images by the offiicial Kitti providers. Some researchers interpolate themselfs using different methods and some use the interpolated for visualization only and some use it for training and none (as far as I know) use it for quantitative evaluation. or quantitative evaluation it's either 1) or 2) and I suggest use 2) and submit your result to the benchmark.

**Comment by koutilya40192** [comment]
Thanks for your responses @a-jahani and @ClementPinard . That really clears a lot of my doubts.
