### ISSUE TITLE
Normalization of cam_coords in inverse_warp

### ISSUE THREAD

**Issue by plaut** [ClementPinard/SfmLearner-Pytorch#49]
Shouldn't `cam_coords` be normalized by its L2 norm before multiplying by the depth?
i.e., add:
`cam_coords /= torch.norm(cam_coords, p=2, dim=1, keepdim=True)`
before this line:
https://github.com/ClementPinard/SfmLearner-Pytorch/blob/a866333f043f9f42d020c374bfc5d2134436862f/inverse_warp.py#L40

**Comment by ClementPinard** [comment]
depth is not distance to the camera ! It's actually the z coordinate, hence the third point coordinate set to 1.
