### ISSUE TITLE
bugs 

### ISSUE THREAD

**Issue by tjufan** [ClementPinard/SfmLearner-Pytorch#50]
In Inverse_warp.py, the line 40, 
cam_coords = (intrinsics_inv @ current_pixel_coords).reshape(b, 3, h, w)
SyntaxError: invalid syntax
what is @ used for? a decorator, or an operator? The paltform I used is python 2.7 anaconda

**Comment by ClementPinard** [comment]
It's the python3 equivalent of torch.bmm si you can replace it that way.

However i really advice you to test this code on python3, as i did not do any compatibility test with python 2

**Comment by tjufan** [comment]
thx, i will test the code in python3发自我的华为手机-------- 原始邮件 --------主题：Re: [ClementPinard/SfmLearner-Pytorch] bugs  (#50)发件人：Clément Pinard 收件人：ClementPinard/SfmLearner-Pytorch 抄送：tjufan ,Author It's the python3 equivalent of torch.bmm si you can replace it that way.
However i really advice you to test this code on python3, as i did not do any compatibility test with python 2
