### ISSUE TITLE
Inconsistent results with test pretrained posenet model

### ISSUE THREAD

**Issue by rockylu1995** [ClementPinard/SfmLearner-Pytorch#53]
I used the Odometry dataset and the pretrained model of PoseNet that you guys provided in the Goole drive to test on Sequence 09 and 10. However, I did not get the same results that you guys showed on the github. Do you guys update the model after finishing the read me page?

**Comment by ClementPinard** [comment]
You are right, I forgot to update these results.
I comes from the fact that the new training workflow got better results, but only for checkpoint model and not mode_best, so the pose is not consistent with the bast depth model. Didn't know what to do with that (are we better off than before ? Depends on what your prioritize !)

Here are my results for current archived networks :
model_best :

09 : ATE 0.0195 (std 0.0106), RE 0.0041 (std 0.0022)
10 : ATE 0.0148 (std 0.0096), RE 0.0042 (std 0.0026)

checkpoint :

09 : ATE 0.0141 (std 0.0084) RE 0.0031 (std 0.0020)
10 : ATE 0.0116 (std 0.0096) RE 0.0042 (std 0.0023)
