### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by mathmanu** [ClementPinard/SfmLearner-Pytorch#6]
In the README.md, you mention:
**pytorch 0.3**
scipy
argparse
tensorboard-pytorch
tensorboard
blessings
progressbar2
path.py

Is there a mistake?  Pytorch 0.2 seems to be latest version.

**Comment by ClementPinard** [comment]
Nothing official for the moment, but 0.3 release is coming within a few days. (actually it was supposed to come out last tuesday but they got some problems I believe) When it's released, this comment will make much more sens ;)

You can get download instructions to get it here : https://gist.github.com/soumith/c1792cd67a22094e37866c2677b85432
