### ISSUE TITLE
Bug with photometric_reconstruction_loss in train.py line 386

### ISSUE THREAD

**Issue by zxcvfd13502** [ClementPinard/SfmLearner-Pytorch#61]
Hello Clement Pinard. Thank you for offering such a good implementation in Pytorch.
I meet a bug when running the training process.
In _train.py_ line 386 you used 
  _loss_1 = photometric_reconstruction_loss(tgt_img, ref_imgs,
                                                 intrinsics, **intrinsics_inv,**
                                                 depth, explainability_mask, pose,
                                                 args.rotation_mode, args.padding_mode)_
But indeed the _photometric_reconstruction_loss_ function just takes 6-8 arguments, and I'm not clear about what **intrinsics_inv** is. Should we transfer this into the _photometric_reconstruction_loss_ function?

**Comment by zxcvfd13502** [comment]
And the same bug happens to **inverse_warp** in line 411

**Comment by ClementPinard** [comment]
I see the problem, I updated the code to work without pre-inverted intrinsics matrices, but it didn't do it for the validation code.

A patch is coming
