### ISSUE TITLE
About loading the intrinsics in kitti_raw_loader.py

### ISSUE THREAD

**Issue by gengrui1983** [ClementPinard/SfmLearner-Pytorch#64]
Hi Clement,

Sorry that this might be an easy question but it is really the one confusing me quite a while. 

This is how you get the intrinsic.
https://github.com/ClementPinard/SfmLearner-Pytorch/blob/94b261942a618cfbfa612a91c46c1922adbb3320/data/kitti_raw_loader.py#L178

I remember the P_rect is a 3x4 matrix, but why the P_rect[:, :3] is the intrinsic? Could you please help to give more details on it?

Thank you very much.

Regards,
Rui

**Comment by ClementPinard** [comment]
P_rect IS the intrinsics matrix of rectified frames. The last row is the lateral shift between left frame and right frame (in terms of pixels, relative to the focal length).

In the metadata there are several matrices, most of them are regular rotation translation matrices, like R_rect. The P matrix on the contrary is related to the frame space.

**Comment by gengrui1983** [comment]
Thank you @ClementPinard !
