### ISSUE TITLE
Problem about unit

### ISSUE THREAD

**Issue by mike112223** [ClementPinard/SfmLearner-Pytorch#66]
Hi Clement
I'm confused about the unit of results. Since using unsupervised learning to train, there is not supervised signals. Why is the results in meters?
I suppose that it is because of the unit of intrinsics. Am i right? if I correct, then I change the unit of intrinsics, the results will change as well.

Thank you so much!!

**Comment by ClementPinard** [comment]
The unit of intrinsics is in pixels and I would not advise to change them :)

However, quality measurement is in meters because the scaling factor is applied so that median values of estimation and ground truth are the same. As such the results will have the same unit as the ground truth

**Comment by mike112223** [comment]
So if the ground truth is in other unit, then I can also use scaling factor to scale the results to that unit.

**Comment by ClementPinard** [comment]
Yes, and the error measurement units will change accordingly.

Most of them are actually unit-less though. 
Abs diff and sq_rel will have unit error, but all other error functions are unit-less

**Comment by mike112223** [comment]
Thank you!
