### ISSUE TITLE
Error during test

### ISSUE THREAD

**Issue by mathmanu** [ClementPinard/SfmLearner-Pytorch#7]
I get the following error when trying to do test:

Traceback (most recent call last):
  File "test_disp.py", line 144, in <module>
    main()
  File "test_disp.py", line 50, in main
    pose_net.load_state_dict(weights['state_dict'], strict=False)
TypeError: load_state_dict() got an unexpected keyword argument 'strict'

Please help.

**Comment by ClementPinard** [comment]
see pytorch docs for an explanation of `strict` option, you need last version `0.3.0` , problem related to #6 
http://pytorch.org/docs/master/nn.html?highlight=load_state_dict#torch.nn.Module.load_state_dict

In the meantime if you want to wait for official release of `0.3.0`, you can simply remove this keyword and set `output_exp=True` in the line above (but inference will be slower)

**Comment by mathmanu** [comment]
Thanks. That fix worked.
