### ISSUE TITLE
Seeking help for understanding 'odo_pose = imu2cam @ np.linalg.inv(origin) @ pose_matrix @ np.linalg.inv(imu2cam)'

### ISSUE THREAD

**Issue by sconlyshootery** [ClementPinard/SfmLearner-Pytorch#71]
Thank you for your nice sharing, your code is very nice!
I got trouble in understanding a line in kitti_raw_loader.py at  row 171---"odo_pose = imu2cam @ np.linalg.inv(origin) @ pose_matrix @ np.linalg.inv(imu2cam)", I didn't understand why imu2cam and its inverse are used at the same time, and the variable 'origin' seems to equal pose matrix, so to my understanding, this term equals to an identity matrix.

**Comment by ClementPinard** [comment]
Origin only equals first pose matrix.

That way we have the same format as kitti odometry, which are 3x4 matrix relative to the first image and not to the world. As such the first outputted matrix will indeed be the exact identity but it won't be the case for further ones.

**Comment by AdamAsh2019** [comment]
but.......how to understand why imu2cam and its inverse are used at the same time??
