### ISSUE TITLE
A bug in run_inference.py

### ISSUE THREAD

**Issue by MingkangXiong** [ClementPinard/SfmLearner-Pytorch#73]
https://github.com/ClementPinard/SfmLearner-Pytorch/blob/8b8398433709b8aa77e021caea64ab48207c8ef5/run_inference.py#L66

It should be 
`tensor_img = ((tensor_img/255 - 0.5)/0.5).to(device)`

**Comment by ClementPinard** [comment]
You are right, thanks for pointing it out
