### ISSUE TITLE
Prepare_train_data

### ISSUE THREAD

**Issue by danbo2** [ClementPinard/SfmLearner-Pytorch#76]
Hi all,

Does someone meet this error when executing prepare_train_data ? 
![98](https://user-images.githubusercontent.com/16380245/68952950-d8aa2080-078e-11ea-857a-3fc2408cb239.PNG) I have checked the kitti raw dataset, and I am sure there is no 00000028.bin in this folder. Can anyone help me ?

Thanks

**Comment by lambert-x** [comment]
Hi guy,
I am facing the same problem. Have you solved it?

**Comment by danbo2** [comment]
@lambert-x You can change the training dataset.

**Comment by lambert-x** [comment]
> @lambert-x You can change the training dataset.

You mean just training with the rest of the dataset?

**Comment by danbo2** [comment]
@lambert-x change training dataset in python script

**Comment by ClementPinard** [comment]
What exact command did you try? The bin files are the lidar frames, have you only downloaded images or groundtruth too?

**Comment by luyao777** [comment]
Hi, I met the same problem. 
After I use the script provided on the official website and I use the command as follows:
> python data/prepare_train_data.py $DATASET --dataset-format 'kitti_raw' --dump-root $TRAIN_SET --width 832 --height 256 --num-threads 4 --static-frames $STATIC_FILES --with-depth

How do you solve the problem?
