### ISSUE TITLE
Multi scale training

### ISSUE THREAD

**Issue by mathmanu** [ClementPinard/SfmLearner-Pytorch#8]
The original SfMLearner uses a MultiScale approach for training (4 different scales/resolutions to train together). However this code is using a RandomScale apprach and seen in the set of augmentations:

    input_transform = custom_transforms.Compose([
        custom_transforms.RandomHorizontalFlip(),
        custom_transforms.RandomScaleCrop(),
        custom_transforms.ArrayToTensor(),
        normalize
    ])

I feel that MultiScale approach will be better since Pose and depth may be dependent on scale.

This is not really an issue but a request to support MultiScale training instead of RandomScale.

**Comment by ClementPinard** [comment]
DispNet actually computes different scales, so we are already doing multi scale training.

The random scale crop transformation is actually taken from https://github.com/tinghuiz/SfMLearner/blob/master/data_loader.py#L83

So both code are doing mult scale training AND Random scale crop
