### ISSUE TITLE
where is the model save？

### ISSUE THREAD

**Issue by yxh1993** [ClementPinard/SfmLearner-Pytorch#81]
when I input ''python3 run_inference.py --pretrained /path/to/dispnet --dataset-dir /path/pictures/dir --output-dir /path/to/output/dir'', I want to know where is the disnet and what is disnet mean.

And I also want to know what is dataset-dir mean and where is it.

**Comment by ClementPinard** [comment]
DispNet is the network used to compute the depth. I actually outputs the inverse of depth, which is in a stereo camera the disparity, hence the name. It is usually located in the `checkpoints` folder, but you can download the pretrained version [here](https://drive.google.com/drive/folders/1H1AFqSS8wr_YzwG2xWwAQHTfXN5Moxmx) (from the README) and put it anywhere you like.

The dataset-dir option is a folder with pictutes in it. The inference script will then try to compute the depth map of each picture in the folder you will give it, and save the result as a numpy array or vizualisation picture in the folder `/path/to/output/dir`
