### ISSUE TITLE
How to visualize pose

### ISSUE THREAD

**Issue by Samyer** [ClementPinard/SfmLearner-Pytorch#82]
Hi,
How your code as well as explained in the paper seem using 3-frame snippets for prediction, therefore the output final_poses has size [pics_number, frame_number, 3, 4] while KITTI ground truth poses data only has size [pics_number, 3, 4]. I don't know how to deal with this array to draw visual odometry map so could you please show me how to do it?

**Comment by ClementPinard** [comment]
Hi, I can see you already aksed for it in issue #39 , And I cannot explain things more than what I already did there.

I might add a script to get a vizualisation, but as discussed there, there as multiple different ways of vizualising the result, as you will get overlapping poses.

A very simple algorithm proposition, using the fact in every snippet of `n` frames, poses are given relatively to the first of the snippet (Yes, it means that for every row, the first [3,4] matrix transformation is identity) :
 - load `predictions.npy`
 - first output pose is identity
 - for each row in `predictions`:
    - get the second pose (so the first one that is not identity), and since it is given relatively to previous pose
    - multiply it with the pose in last row of output poses. This will make the pose absolute instead of relative.
    - append it to the array of output poses

You will normally have an array XYZ given with respect to the first frame of the whole sequence and not only the snipped it was estimated within. Keep in mind that this is only a first naive visualization, which does not use the fact that a snippet has 3 to 5 frames and not only two ! 

Hope it helped

Clément

**Comment by h-gokul** [comment]
```
from scipy.spatial.transform import Rotation as R


def to_4x4(pose3x4):
    pose4D = np.eye(4, dtype = np.float64)
    pose4D[:3,:] =  pose3x4
    return np.matrix(pose4D) 

def SE2se(SE_data):
    """
    Converts a relative pose matrix (4x4)
    to euler format (1x6)
    """
    def SO2so(SO_data):
        return R.from_dcm(SO_data).as_rotvec()

    result = np.zeros((6))
    result[0:3] = np.array(SE_data[0:3,3].T)
    result[3:6] = SO2so(SE_data[0:3,0:3]).T
    return result

def rel_snips2abs(poses):
    output_poses = []
    pose = np.matrix(np.eye(4))
    for i, snippet in enumerate(poses):  # for every snippet,
        # multiply second relpose in snippet with prevpose 
        pose = pose * to_4x4(snippet[1]) 
        pose1x6 = SE2se(pose)
        output_poses.append(pose1x6)
    return np.array(output_poses)  
```

pass your predictions to  rel_snips2abs() function. I tried to follow clement's algorithm as closely as possible here.
Let me know if there are mistakes
