### ISSUE TITLE
AttributeError: 'list' object has no attribute 'detach'

### ISSUE THREAD

**Issue by lordbutters** [ClementPinard/SfmLearner-Pytorch#89]
Sorry for disturb you.
When I run **_train.py_**, I got a mistake , I dont know how to solve it, could you tell me what should I do to run the **_train.py_** correctly? 
Here is the error message:

**_Traceback (most recent call last):
  File "train.py", line 460, in <module>
    main()
  File "train.py", line 219, in main
    errors, error_names = validate_without_gt(args, val_loader, disp_net, pose_exp_net, epoch, logger, tb_writer)
  File "/home/jie_r/.conda/envs/sfmlearner/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
100% (200 of 200) |##############################################################| Elapsed Time: 0:04:32 Time:  0:04:32
  File "train.py", line 372, in validate_without_gt
    log_output_tensorboard(tb_writer, 'val', i, '', epoch, 1./disp, disp, warped, diff, explainability_mask)
100% (3000 of 3000) |############################################################| Elapsed Time: 0:04:32 Time:  0:04:32
    warped_to_show = tensor2array(warped_j)
  File "/home/jie_r/SfmLearner-Pytorch-master/utils.py", line 87, in tensor2array
100% (753 of 753) |##############################################################| Elapsed Time: 0:00:00 Time:  0:00:00
AttributeError: 'list' object has no attribute 'detach'_**

**Comment by ClementPinard** [comment]
For the context, warped_j is supposed to be a tensor, not a list. Going upward, warped is supposed to be a list of tensors, which we unpack at line https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/utils.py#L75

Did you change something in the function `photometric_reconstruction_loss` ? Or maybe in the function `log_output_tensorboard` ?

**Comment by lordbutters** [comment]
> For the context, warped_j is supposed to be a tensor, not a list. Going upward, warped is supposed to be a list of tensors, which we unpack at line https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/utils.py#L75
> 
> Did you change something in the function `photometric_reconstruction_loss` ? Or maybe in the function `log_output_tensorboard` ?

I have deleted the old folder and download a new one from your github, then run the train.py again. Unfortunately, I get the same error message. 
I forgot to tell you that when I run train.py, the fisrt 3000 training is normal, when the first 3000 training has done, the error message appears.

**Comment by qinzhang2016** [comment]
I got the same error as @lordbutters. Look forward to knowing how to solve it.

**Comment by qinzhang2016** [comment]
I got the same error as @lordbutters. Look forward to knowing how to solve it. 
As below is the error message. After the first 3000 has done, the error comes.

* Avg Loss : 0.660
100% (3000 of 3000) |####################| Elapsed Time: 0:10:18 ETA:  00:00:00
ional.py:2693: UserWarning: Default grid_sample and affine_grid behavior will be changed to align_corners=False from 1.4.0. See the documentation of grid_sampleN/A% (0 of 340) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
  warnings.warn("Default grid_sample and affine_grid behavior will be changed "
Traceback (most recent call last):
  File "train.py", line 453, in <module>
    main()
  File "train.py", line 212, in main
    errors, error_names = validate_without_gt(args, val_loader, disp_net, pose_exp_net, epoch, logger, tb_writer)
  File "/home/qinzhang/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "train.py", line 365, in validate_without_gt
    log_output_tensorboard(tb_writer, 'val', i, '', epoch, 1./disp, disp, warped, diff, explainability_mask)
  File "/home/qinzhang/code/SfmLearner-Pytorch-master/utils.py", line 77, in log_output_tensorboard
    warped_to_show = tensor2array(warped_j)
  File "/home/qinzhang/code/SfmLearner-Pytorch-master/utils.py", line 87, in tensor2array
    tensor = tensor.detach().cpu()
AttributeError: 'list' object has no attribute 'detach'

**Comment by lordbutters** [comment]
@ClementPinard I have not solve it until now, and @qinzhang2016  got the same question. Is it possible that something goes wrong with the code?

**Comment by ClementPinard** [comment]
I am not able to run my code for now, as o dont have Access to a gpu for the moment.

The best you can try is to print the list that is given to the function `tensor2array` in the function `log_output_tensorboard` : I strongly suspect it is a list of tensors (possibly with only one element)

**Comment by qinzhang2016** [comment]
Yes, you are right. I print the warped_j and it is a two elements list of tensors, but the second tensor is all zero. Also diff_j is a list of tensors, and the second element is all zero. I replace warped_j to warped_j[0] and diff_j to diff_j[0], the problem is solved.  But I still wondered why.

**Comment by lordbutters** [comment]
> Yes, you are right. I print the warped_j and it is a two elements list of tensors, but the second tensor is all zero. Also diff_j is a list of tensors, and the second element is all zero. I replace warped_j to warped_j[0] and diff_j to diff_j[0], the problem is solved. But I still wondered why.

@ClementPinard thanks for @qinzhang2016  help, your solution works! Thank you both!

**Comment by lordbutters** [comment]
> Yes, you are right. I print the warped_j and it is a two elements list of tensors, but the second tensor is all zero. Also diff_j is a list of tensors, and the second element is all zero. I replace warped_j to warped_j[0] and diff_j to diff_j[0], the problem is solved. But I still wondered why.

Have you do inference? I can't figure out how to do inference, which testset did you use? It seems that the kitti-raw set has been divided into trainset and valset and  I can't find testset.

**Comment by qinzhang2016** [comment]
@lordbutters The train and test set are recorded in two text files. If you run the prepare_train_data, you will find them in the data fold.

**Comment by qinzhang2016** [comment]
@lordbutters I haven't done the inference because my training process is stopped dut to lack of memory. But I noticed two test files named test_disp.py and test_pose.py. I think they are the inference code.

**Comment by lordbutters** [comment]
> @lordbutters The train and test set are recorded in two text files. If you run the prepare_train_data, you will find them in the data fold.

I got two files, train.txt and val.txt, I didn't find the test.txt.

**Comment by ClementPinard** [comment]
The eigen split test files can be accessed here : https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/kitti_eval/test_files_eigen.txt

See the readme to run test disp on it.

For test pos, you need the kitti odometry dataset

**Comment by ClementPinard** [comment]
solved in the last commit
