### ISSUE TITLE
Inference quality is not good

### ISSUE THREAD

**Issue by mathmanu** [ClementPinard/SfmLearner-Pytorch#9]
The quality of depth generated during inference is much poorer compared to that seen on tensorboard (during training).

Here is an example inference output:
![0000000000_disp](https://user-images.githubusercontent.com/2990503/33541599-b2377cd2-d8f5-11e7-9591-e85a73bf912f.png)

It seems inference is not working correctly.

**Comment by ClementPinard** [comment]
Try to update your code, I pushed different max values for disp and depth. Disp is now normalized dans depth is maxed to 10 (instead of 1 originally)

**Comment by mathmanu** [comment]
It's better now. Thanks.
