### ISSUE TITLE
Confusion about the 'src_pixel_coords' parameter in function 'F.grid_sample'

### ISSUE THREAD

**Issue by pleasegostraight** [ClementPinard/SfmLearner-Pytorch#93]
Hi @ClementPinard ,

Thanks for you work. I'm confused about the second parameter 'src_pixel_coords' of function 'F.grid_sample'. 
`projected_img = F.grid_sample(img, src_pixel_coords, padding_mode=padding_mode, align_corners=True)`
The last dimension of that parameter seems to be the input pixel locations, but in your code, it seems to be the output pixel locations.Why?

Thanks

**Comment by ClementPinard** [comment]
It's a question of terminology.
Output pixel location *per se* will follow `src_pixel_coords` shape, so you don't need to specify it.
What i (maybe wrongly) called output pixel location is where we pick the color in img for each pixel.

The `project_img` at (i,j) will be computed from the coordinates (x,y) regarding `img`, located at rc_pixel_coords` (i,j) . So depending on what you call output pixel location, (i,j) or (x,y) you might have different terminology.

**Comment by pleasegostraight** [comment]
Thanks for your reply.
Follow your description, the aim of this function is to project `img` coordinates(x,y) to `project_img` coordinate (i,j)(In SFMLearner is to project the last image to the next image).
My question is in the official description of function `grid_sample`, the shape of the second parameter 'grid' is [b,h,w,2], and the last dimension of the second parameter 'grid'(2) should be(x,y) (`img` coordinate),such as [b,j,i,(x,y)]:
![image](https://user-images.githubusercontent.com/25680013/80363770-48344800-88b7-11ea-8df8-6ac2a8c8f787.png)
But I'm confused in your code, the last dimension of the parameter 'grid' seems to be(i,j) (`project_img` coordinate),such as [b,y,x,(i,j)], it seems different as official description, and may influence results?

**Comment by ClementPinard** [comment]
not sure where you are confused in the code, the grid coordinates are the (x,y) coordinates of `img`

When there is no movement, (x,y) and (i,j) will be the same, which is why you may be confused. But when there is a movement, pixels are transofrmed with the function `cam2pixel` (here we talk about the pixel coordinate in img, i.e. (x,y))

**Comment by pleasegostraight** [comment]
For example, I want to project the (x,y) coordinate of `img` to the (i,j) coordinate of `project_img`, and in the second parameter of function `grid_sample`('grid'), the corresponding element should be [b,j,i,(x,y)]. But in the code it is [b,y,x,(i,j)], it seems to inverse the `img` coordinate and the `project_img` coordinate in the parameter 'grid', am I right?

**Comment by pleasegostraight** [comment]
And the result of the function `grid_sample` in the code seems to project the (i,j) coordinate of `project_img` to the (x,y) coordinate of `img`(because the error in the the second parameter of that function, as I previously said), contrary to our purpose?

**Comment by ClementPinard** [comment]
You have to tell how you understand that we construct `[b,y,x(i,j)]`instead of `[b,j,i,(x,y)]` because for me it's very clear that we construct the right grid.

To convince you, you can see how the   `src_pixel_coords` is constructed, with the two sub coordinates `X_norm` and `Y_norm`, which are respectively  `[b,j,i,(x)]` and `[b,j,i,(y)]` and then stacked together : https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/inverse_warp.py#L65

I can actually there's been a small mistake because I called the return value of `cam2pixel` `pixel_coords` just like the global vairable, which can be confusing, but has no practical effect of how we compute this grid

**Comment by pleasegostraight** [comment]
In my understanding, the aim of function `cam2pixel` is to compute the `projected_img` pixel (i,j) which matches the `img` pixel (x,y), `X_norm` and `Y_norm` is the pixel coordinate wihch `cam2pixel` function computed, corresponding to the pixel we want to projected to, means (i,j) respectively. So to my understanding, `X_norm` and `Y_norm` means `[b,y,x,(i)]` and `[b,y,x,(j)]`?

**Comment by ClementPinard** [comment]
No, that's the other way around. we are searching for pixel (x,y) in `img` that would be the same color as the pixel situated in `(i,j)` , which is the coordinate of every 2d vector of `src_pixel_coords` 
`src` refered to `img` , be casue we will sample colors from `img` (it's the source of the color information).

The whole operation is this way : 
for each point in target image (note here, that the tgt_img tensor is never used) i,j in [0,H]x[0,W], get the corresponding coordinates of source image. The sampled color at `img[n, x, y]` should be the same as `tgt_img[n, i, j]` . Note also that `x,y` are float values, `i,j` are integers (we use bilinear sampling to get `img[n,x,y]` ), all of this is given the depth for `tgt_img`and the displacement `R,t` from `src_img` to `tgt_img`

for n,i,j integers in [0,B]x[0,H]x[0,W] (n is batch number)
 1. get 3D position of point in coordinates i,j with depth d[n,j,i] with resepct to tgt_img : this is done in pixel2cam
 2. get 3D position of pointwith respect to src_img : this is done in the main function inverse_warp
 3. deduce pixel position (x,y) in src_img image plane : this is done in the function cam2pixel
 4. sample the color src_img[n,x,y] using grid_sample

**Comment by pleasegostraight** [comment]
Get it! So the depth map from `disp_net` is for `tgt_img`?

**Comment by ClementPinard** [comment]
Yes ! 
you can read the original paper for more details about this, but even if we do multiple warps, we only compute one depth, for tgt_img from tgt_depth and src_img poses, we try to reconstruct tgt_img : we take colors from source images to hopefully reconstruct the target image, and the target image is always the same, at the middle of the snippet, be it  or  frames (or more if you want)

**Comment by pleasegostraight** [comment]
Thanks very much
