### ISSUE TITLE
How dataload the sequence image?

### ISSUE THREAD

**Issue by QQQJG** [ClementPinard/SfmLearner-Pytorch#95]
I have some question when you load the image. For "imgs = [stack[:, i * w_img:(i + 1) * w_img] for i in range(sequence_length)]". This is the mode of stack,. I can't understand you load an image. And divide this picture into three. 
So I can't understand the mean of this.

**Comment by ClementPinard** [comment]
Hi, see the data code for the original code here : https://github.com/tinghuiz/SfMLearner/blob/master/data/prepare_train_data.py#L33

The main foal of the stacked dataset was to be compliant with the original dataset for this paper. But I highle recommend you use the regular sequence folder : it's much simpler and faster. However, you cannot have multiple intrinsics in the same folder (but for that you just use different folders)
