### ISSUE TITLE
prepare_train_data.py for cityscapes results in  empty train.txt, val.txt

### ISSUE THREAD

**Issue by InnovArul** [ClementPinard/SfmLearner-Pytorch#96]
I am running the following command for preparing cityscapes data:

```
python data/prepare_train_data.py /media/data1/datasets/cityscapes --dataset-format 'cityscapes' --dump-root ./formatted_data --width 416 --height 171 --num-threads 1
```

In the end, the `./formatted_data` folder contains only two empty text files `train.txt`, `val.txt`.
Any pointers on what could have gone wrong?

**Comment by InnovArul** [comment]
it turns out that in cityscapes dataset, the order of scene_id, frame_id is different than whats programmed in `data/cityscapes_loader.py`. I am not sure what caused this change. 
I have fixed it and created a pull request. Pl. review the changes once (especially related to intrinsics filenames).

**Comment by ClementPinard** [comment]
Thanks for your help! Not sure what caused this problem, maybe they changed the metadata format.
