### ISSUE TITLE
Do you have IMU data in KITTI?

### ISSUE THREAD

**Issue by QQQJG** [ClementPinard/SfmLearner-Pytorch#99]
I'm sorry to ask you something that is not related to SFMLearner, but I hope I can ask you about IMU data. Because My attention is the fuse of IMU and visual. But I can't download the IMU data from the KITTI. So here I ask you if you have KITTI ’s IMU data.
   Thanks!

**Comment by SenZHANG-GitHub** [comment]
> ```
> I'm sorry to ask you something that is not related to SFMLearner, but I hope I can ask you about IMU data. Because My attention is the fuse of IMU and visual. But I can't download the IMU data from the KITTI. So here I ask you if you have KITTI ’s IMU data.
> ```
> 
> Thanks!

You can find the IMU records in raw KITTI datasets which can be downloaded from the KITTI project page. However, be aware that those IMU records are not synchronized with the images. Though you can do manual alignment using the timestamp, it should still be noisy
